import PDFDocument from "pdfkit";
import Payment from "../models/Payment.js";

export const downloadPayslip = async (req, res) => {
  const payment = await Payment.findOne({
    _id: req.params.id,
    createdBy: req.user._id,
  }).populate("worker", "name role phone city dailyWage minimumWage");

  if (!payment) {
    res.status(404);
    throw new Error("Payment not found");
  }

  const worker = payment.worker;

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=${worker.name}-${payment.month}-payslip.pdf`
  );

  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(res);

  doc.fontSize(26).text("FairFundz", { align: "center" });
  doc.fontSize(12).text("Salary Slip / Wage Payment Receipt", {
    align: "center",
  });

  doc.moveDown(2);

  doc.fontSize(16).text("Worker Details", { underline: true });
  doc.moveDown();

  doc.fontSize(12).text(`Name: ${worker.name}`);
  doc.text(`Role: ${worker.role}`);
  doc.text(`Phone: ${worker.phone}`);
  doc.text(`City: ${worker.city}`);
  doc.text(`Month: ${payment.month}`);

  doc.moveDown(2);

  doc.fontSize(16).text("Attendance Summary", { underline: true });
  doc.moveDown();

  doc.fontSize(12).text(`Present Days: ${payment.presentDays}`);
  doc.text(`Half Days: ${payment.halfDays}`);
  doc.text(`Absent Days: ${payment.absentDays}`);

  doc.moveDown(2);

  doc.fontSize(16).text("Wage Summary", { underline: true });
  doc.moveDown();

  doc.fontSize(12).text(`Daily Wage: ₹${worker.dailyWage}`);
  doc.text(`Minimum Wage: ₹${worker.minimumWage}`);
  doc.text(`Payment Status: ${payment.status}`);

  doc.moveDown();

  doc.fontSize(18).text(`Total Salary: ₹${payment.totalAmount}`, {
    align: "right",
  });

  doc.moveDown(2);

  const compliance =
    worker.dailyWage >= worker.minimumWage
      ? "Compliant"
      : "Below Minimum Wage";

  doc.fontSize(12).text(`Compliance Status: ${compliance}`);

  doc.moveDown(3);

  doc.text(`Generated Date: ${new Date().toLocaleDateString()}`);
  doc.text("Generated by FairFundz Payroll System");

  doc.end();
};